name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13" # Use Python 3.13

      # Install Poetry
      - name: Install Poetry
        run: pip install poetry

      # Set up Poetry and install dependencies
      - name: Set up Poetry
        run: poetry install --no-root

      # Run linting and formatting
      - name: Run linting and formatting
        run: poetry run make lint

      # Run tests
      - name: Run tests
        run: poetry run make test
